# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170722_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
