# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bid_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_bidded',
            field=models.BooleanField(default=False),
        ),
    ]
