# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_post_is_bidded'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_bidded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected', to=settings.AUTH_USER_MODEL),
        ),
    ]
